# Single packages with large dependency trees

[tensorflow]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["tensorflow"]

[dask]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["dask"]

[dagster]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["dagster"]

[spacy]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["spacy"]

[prefect]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["prefect"]

[kedro]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["kedro"]

[salt]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["salt"]

[pyinfra]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["pyinfra"]

[flair]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["flair"]

[stanza]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["stanza"]

[holoviews]
resolution = "lowest-direct"
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07 14:00:00"
requirements = ["holoviews"]
