"""Write the generated files from the option declaration.

The declaration in :mod:`nab.optiontable` is what a person edits; this
turns it into the literals the parser and the help pages read, and into
the global-flag table on the CLI reference page::

    python tasks/gen_cli.py --write     # rewrite the generated module
    python tasks/gen_cli.py --check     # fail, with a diff, when it is stale

``tests/test_cli_generated.py`` runs ``--check`` in a subprocess on every
cell of the test matrix, which is what makes the generated file impossible
to leave stale.  A pre-commit hook cannot do it: every hook here runs in
its own isolated environment and none of them can import ``nab``.

The page check lives here rather than in ``Opt.__init__``: the sdist ships
``src/nab`` and ``tests`` alone, so a file-exists check at import time would
raise on every installed nab.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from nab import optiondefs
from nab.optiondefs import COMMANDS, UNSET, Kind, Opt
from nab.optiontable import ALL

_ROOT = Path(__file__).resolve().parents[1]
_SPEC = _ROOT / "src" / "nab" / "_cli" / "spec.py"
_DOCS = _ROOT / "docs"
_REFERENCE = _DOCS / "reference" / "cli.md"

# What the generated block on the reference page is fenced by.  The opening
# line says where the rows come from, because that is where a reader who
# wants to change one has to go.
_OPEN = (
    "<!-- generated by tasks/gen_cli.py --write from nab/optiondefs.py; do not edit -->"
)
_CLOSE = "<!-- /generated -->"

# The generated file is formatter-exempt, so the generator owns its width.
_WIDTH = 88

_INDENT = "    "

# The kinds that store a constant instead of reading a value.
_CONST_KINDS = frozenset({Kind.FLAG, Kind.TRI, Kind.COUNT, Kind.EAGER})

_HEADER = '''"""Every option nab takes, as literals.

Generated by ``tasks/gen_cli.py --write`` from :mod:`nab.optiondefs`.  Do
not edit it: the next run of the generator would drop the edit, and
``tests/test_cli_generated.py`` fails while the two disagree.

The module holds no ``def``, no ``if``, no comprehension and no import, so
importing it is the whole of its coverage and nothing here can be wrong at
run time in a way a test would have to reach.

A row is ``(long, short, kind, dest, vtype, choices, const, default,
required, help)``.  ``vtype`` carries a trailing ``?`` when the literal
string ``None`` is accepted and means unset.  ``const`` is what one
occurrence stores when it reads no value, and ``help`` indexes
:data:`HELP`, so a negation and the row it negates share one string.

The formatter is off over the tables: it would put every field of a long
row on a line of its own, and the generator wraps them to the same width
instead.
"""
'''


def main(argv: list[str] | None = None) -> int:
    """Write or check the generated module, returning the process status."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="rewrite the module")
    action.add_argument("--check", action="store_true", help="report a stale module")
    arguments = parser.parse_args(argv)

    optiondefs.validate(ALL)
    _check_pages()

    wanted = [(_SPEC, _module_text()), (_REFERENCE, _reference_text())]
    if arguments.write:
        for path, text in wanted:
            path.write_text(text, encoding="utf-8")
        return 0

    return max(_report(path, text) for path, text in wanted)


def _report(path: Path, wanted: str) -> int:
    """Compare one generated file on disk with what the declaration wants."""
    found = path.read_text(encoding="utf-8") if path.exists() else ""
    if found == wanted:
        return 0

    relative = path.relative_to(_ROOT).as_posix()
    diff = difflib.unified_diff(
        found.splitlines(keepends=True),
        wanted.splitlines(keepends=True),
        fromfile=f"{relative} (on disk)",
        tofile=f"{relative} (from nab/optiontable.py)",
    )
    sys.stdout.writelines(diff)
    sys.stdout.write(f"\n{relative} is stale; run: python tasks/gen_cli.py --write\n")
    return 1


def _reference_text() -> str:
    """Rebuild the CLI reference page around its global-flag block.

    Everything outside the two markers is prose a person maintains; the
    block between them is the seven root rows, so the page cannot describe
    a flag the declaration does not carry.
    """
    page = _REFERENCE.read_text(encoding="utf-8")
    head, opened, rest = page.partition(_OPEN + "\n")
    _body, closed, tail = rest.partition(_CLOSE + "\n")
    if not opened or not closed:
        msg = f"{_REFERENCE.name} has lost the generated block's markers"
        raise SystemExit(msg)

    return head + opened + _flag_table() + closed + tail


def _flag_table() -> str:
    """Write the global flags as a markdown table, in declaration order."""
    lines = ["| Flag | Effect |", "| ---- | ------ |"]
    for row in ALL:
        if not row.is_global:
            continue
        spelling = f"`{row.cli_flag}`"
        if row.short:
            spelling = f"`-{row.short}`, {spelling}"
        lines.append(f"| {spelling} | {row.help} |")

    return "\n".join(lines) + "\n"


def _check_pages() -> None:
    """Check that every row names a documentation page that exists."""
    for row in ALL:
        page = _DOCS / row.docs
        if not page.is_file():
            msg = f"{row.name} names {row.docs}, which is not a documentation page"
            raise SystemExit(msg)


def _module_text() -> str:
    """Build the whole generated module from the declaration."""
    texts: list[str] = []
    root = _table_lines([row for row in ALL if row.is_global], texts, _INDENT)

    commands: list[str] = []
    for name, _module, _function in COMMANDS:
        rows = [row for row in ALL if not row.is_global and name in row.commands]
        commands.append(f'{_INDENT}"{name}": (')
        commands.extend(_table_lines(rows, texts, _INDENT * 2))
        commands.append(f"{_INDENT}),")

    parts = [
        _HEADER,
        "\n" + _help_block(texts),
        "\n# fmt: off\n",
        _block("ROOT", _ROOT_ANNOTATION, root, "("),
        "\n" + _block("COMMANDS", _COMMANDS_ANNOTATION, commands, "{"),
        "\n" + _dispatch_block(),
        "\n" + _paths_block(),
        "\n# fmt: on\n",
    ]
    return "".join(parts)


# The row type, written out where the generated module cannot import it.
_ROW_TYPE = "tuple[str, str, str, str, str, tuple[str, ...], object, object, bool, int]"

_ROOT_ANNOTATION = f"tuple[\n{_INDENT}{_ROW_TYPE}, ...\n]"

_COMMANDS_ANNOTATION = (
    f"dict[\n{_INDENT}str,\n{_INDENT}tuple[\n"
    f"{_INDENT * 2}{_ROW_TYPE}, ...\n{_INDENT}],\n]"
)


def _block(name: str, annotation: str, lines: list[str], opener: str) -> str:
    """Open and close one annotated table around its rows."""
    closer = ")" if opener == "(" else "}"
    body = "\n".join(lines)
    return f"{name}: {annotation} = {opener}\n{body}\n{closer}\n"


def _help_block(texts: list[str]) -> str:
    """Emit the interned help strings, once the tables have filled them in."""
    lines = [f"{_INDENT}{_literal(text)}," for text in texts]
    body = "\n".join(lines)
    return f"HELP: tuple[str, ...] = (\n{body}\n)\n"


def _dispatch_block() -> str:
    """Each command's module, function and one-line summary."""
    lines = []
    for name, module, function in COMMANDS:
        summary = _summary(module, function)
        fields = [_literal(module), _literal(function), _literal(summary)]
        lines.extend(_wrapped(f'"{name}": (', fields, "),", hanging=_INDENT * 2))

    body = "\n".join(lines)
    return f"DISPATCH: dict[str, tuple[str, str, str]] = {{\n{body}\n}}\n"


def _paths_block() -> str:
    """Emit the dests each command reads as a path, which dispatch coerces."""
    lines = []
    for name, _module, _function in COMMANDS:
        dests = [
            row.dest
            for row in ALL
            if name in row.commands and row.vtype is optiondefs.VType.PATH
        ]
        fields = [_literal(dest) for dest in dests]
        lines.extend(_wrapped(f'"{name}": (', fields, "),", hanging=_INDENT * 2))

    body = "\n".join(lines)
    return f"PATH_DESTS: dict[str, tuple[str, ...]] = {{\n{body}\n}}\n"


def _summary(module: str, function: str) -> str:
    """Read the command's first docstring line, which the root page prints."""
    imported = __import__(module, fromlist=(function,))
    documentation = getattr(imported, function).__doc__ or ""
    return documentation.strip().splitlines()[0]


def _table_lines(rows: list[Opt], texts: list[str], indent: str) -> list[str]:
    """Emit one table, with a generated negation after the row it negates."""
    lines: list[str] = []
    for row in rows:
        index = _intern(texts, row.help)
        lines.extend(_wrapped("(", _fields(row, index), "),", indent))
        if row.negatable:
            lines.extend(_wrapped("(", _negation(row, index), "),", indent))
    return lines


def _fields(row: Opt, index: int) -> list[str]:
    """Write one declared row as the ten literals the walk reads."""
    flag = row.cli_flag or ""
    vtype = "" if row.vtype is None else row.vtype.value
    if vtype and row.nullable:
        vtype += "?"

    const = row.kind in _CONST_KINDS or None
    default = None if row.default is UNSET else row.default

    fields = (
        flag,
        row.short,
        _kind(row),
        row.dest,
        vtype,
        row.choices,
        const,
        default,
        row.required,
        index,
    )
    return [_literal(field) for field in fields]


def _negation(row: Opt, index: int) -> list[str]:
    """Build the ``--no-X`` row, on the same dest with the inverted constant.

    The walk then has no negation branch and ``--no-no-X`` is not a
    spelling anything can produce.
    """
    flag = row.cli_flag or ""
    default = None if row.default is UNSET else row.default
    fields = (
        "--no-" + flag[2:],
        "",
        "neg",
        row.dest,
        "",
        (),
        False,
        default,
        False,
        index,
    )
    return [_literal(field) for field in fields]


def _kind(row: Opt) -> str:
    """Name the row's kind, as the walk spells it."""
    if row.kind is None:
        msg = f"{row.name} has no kind, so it has no command-line surface"
        raise SystemExit(msg)
    return row.kind.value


def _intern(texts: list[str], text: str) -> int:
    """Find ``text`` in ``texts``, adding it when it is new."""
    if text not in texts:
        texts.append(text)
    return texts.index(text)


def _wrapped(
    opener: str,
    fields: list[str],
    closer: str,
    indent: str = _INDENT,
    hanging: str = "",
) -> list[str]:
    """Wrap ``opener``, then ``fields``, then ``closer``, greedily.

    A row's continuation sits at the row's own indent rather than under
    the opening bracket, because one choice set is 79 characters and a
    deeper hanging indent would push it past the width.
    """
    if len(fields) == 1 and opener.endswith("("):
        fields = [fields[0] + ","]

    head = indent + opener
    hanging = hanging or indent

    lines: list[str] = []
    line = head
    for field in fields:
        piece = field if line in (head, hanging) else f", {field}"
        if len(line) + len(piece) + len(closer) <= _WIDTH:
            line += piece
        else:
            lines.append(f"{line},")
            line = hanging + field

    lines.append(line + closer)
    return lines


def _literal(value: object) -> str:
    """Write ``value`` as the source text of a literal, in the house's quotes."""
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, tuple):
        if not value:
            return "()"
        inner = ", ".join(_literal(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    return repr(value)


if __name__ == "__main__":
    raise SystemExit(main())
