"""Generate calls that type-check option rows against command signatures.

Use ``--write`` to update ``tests/cli_bijection.py`` or ``--check`` to report a
diff. Generated calls cannot detect command parameters absent from the declaration.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from nab.optiondefs import COMMANDS, Opt
from nab.optionlower import lower
from nab.optionrows import rows
from nab.optiontable import TABLES

_ROOT = Path(__file__).resolve().parents[1]
_BIJECTION = _ROOT / "tests" / "cli_bijection.py"

_HEADER = '''"""Generated option-row calls for command-signature type checking.

Generated by ``tasks/gen_bijection.py --write`` from :mod:`nab.optiontable`.
Do not edit this file.

Nothing calls these functions. Type checkers compare each call with its command
signature.
"""

from __future__ import annotations

'''


def main(argv: list[str] | None = None) -> int:
    """Write or check the generated module, returning the process status."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="rewrite the module")
    action.add_argument("--check", action="store_true", help="report a stale module")
    arguments = parser.parse_args(argv)

    wanted = _module_text()
    if arguments.write:
        _BIJECTION.write_text(wanted, encoding="utf-8")
        return 0

    return _report(wanted)


def _report(wanted: str) -> int:
    """Compare the file on disk with what the declaration wants."""
    found = _BIJECTION.read_text(encoding="utf-8") if _BIJECTION.exists() else ""
    if found == wanted:
        return 0

    relative = _BIJECTION.relative_to(_ROOT).as_posix()
    diff = difflib.unified_diff(
        found.splitlines(keepends=True),
        wanted.splitlines(keepends=True),
        fromfile=f"{relative} (on disk)",
        tofile=f"{relative} (from nab/optiontable.py)",
    )
    sys.stdout.writelines(diff)
    sys.stdout.write(
        f"\n{relative} is stale; run: python tasks/gen_bijection.py --write\n"
    )
    return 1


def _module_text() -> str:
    """Build the whole generated module."""
    where = _row_names()
    commanded = [
        (path, opt)
        for path, opt in where
        if any(name in opt.commands for name, _m, _f in COMMANDS)
    ]

    imports = [
        f"from {module} import {function}" for _name, module, function in COMMANDS
    ]
    used = sorted({path.split(".")[0] for path, _opt in commanded})
    imports.append(
        "from nab.optiontable import (\n" + "".join(f"    {n},\n" for n in used) + ")"
    )

    calls = [_call(name, function, where) for name, _module, function in COMMANDS]
    return _HEADER + "\n".join(sorted(imports)) + "\n\n\n" + "\n\n".join(calls)


def _row_names() -> list[tuple[str, Opt]]:
    """Pair each declared row's spelling in the generated module with its Opt."""
    return [
        (f"{table.__name__}.{row.name.replace('-', '_')}", lower(row))
        for table in TABLES
        for row in rows(table)
    ]


def _call(name: str, function: str, where: list[tuple[str, Opt]]) -> str:
    """Write one command's call, operands first and then its keywords."""
    carried = [(path, opt) for path, opt in where if name in opt.commands]
    bound = [f"        {path}," for path, opt in carried if opt.is_positional]
    bound += [
        f"        {opt.dest}={path}," for path, opt in carried if not opt.is_positional
    ]

    body = "\n".join(bound)
    return (
        f"def _{function}() -> None:\n"
        f'    """``nab {name}``: {len(bound)} parameters."""\n'
        f"    {function}(\n{body}\n    )\n"
    )


if __name__ == "__main__":
    raise SystemExit(main())
