"""Generate CLI tables and the global-flags reference from ``nab.optiontable``.

Use ``--write`` to update both outputs or ``--check`` to report a diff. Page
validation stays here because installed distributions omit ``docs``.
"""

from __future__ import annotations

import argparse
import difflib
import enum
import inspect
import sys
import textwrap
from dataclasses import MISSING, fields, is_dataclass
from pathlib import Path
from types import FunctionType, MappingProxyType
from typing import TYPE_CHECKING, Any

from nab import optiondefs
from nab.config.ladder import docs_path
from nab.optiondefs import COMMANDS, UNSET, Kind, Opt
from nab.optiontable import ALL

if TYPE_CHECKING:
    from collections.abc import Sequence

    from _typeshed import DataclassInstance

_ROOT = Path(__file__).resolve().parents[1]
_SPEC = _ROOT / "src" / "nab" / "_cli" / "spec.py"
_REGISTRY = _ROOT / "src" / "nab" / "config" / "registry.py"
_DOCS = _ROOT / "docs"
_REFERENCE = _DOCS / "reference" / "cli.md"

# What the generated block on the reference page is fenced by.  The opening
# line says where the rows come from, because that is where a reader who
# wants to change one has to go.
_OPEN = (
    "<!-- generated by tasks/gen_cli.py --write"
    " from nab/optiontable.py; do not edit -->"
)
_CLOSE = "<!-- /generated -->"

# The generated modules are formatter-exempt, so the generator owns their width.
_WIDTH = 88

_INDENT = "    "

# The kinds that store a constant instead of reading a value.
_CONST_KINDS = frozenset({Kind.FLAG, Kind.TRI, Kind.COUNT, Kind.EAGER})

_HEADER = '''"""Generated CLI rows and help strings.

Generated by ``tasks/gen_cli.py --write`` from :mod:`nab.optiontable`.
Do not edit this file.

Rows use ``(long, short, kind, dest, vtype, choices, const, default, required,
help)``. A trailing ``?`` in ``vtype`` accepts ``None``; ``help`` indexes
:data:`HELP`.
"""
'''


def main(argv: list[str] | None = None) -> int:
    """Write or check the generated module, returning the process status."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="rewrite the module")
    action.add_argument("--check", action="store_true", help="report a stale module")
    arguments = parser.parse_args(argv)

    optiondefs.validate(ALL)
    _check_pages()

    wanted = [
        (_SPEC, _module_text()),
        (_REGISTRY, _registry_text()),
        (_REFERENCE, _reference_text()),
    ]
    if arguments.write:
        for path, text in wanted:
            path.write_text(text, encoding="utf-8")
        return 0

    return max(_report(path, text) for path, text in wanted)


def _report(path: Path, wanted: str) -> int:
    """Compare one generated file on disk with what the declaration wants."""
    found = path.read_text(encoding="utf-8") if path.exists() else ""
    if found == wanted:
        return 0

    relative = path.relative_to(_ROOT).as_posix()
    diff = difflib.unified_diff(
        found.splitlines(keepends=True),
        wanted.splitlines(keepends=True),
        fromfile=f"{relative} (on disk)",
        tofile=f"{relative} (from nab/optiontable.py)",
    )
    sys.stdout.writelines(diff)
    sys.stdout.write(f"\n{relative} is stale; run: python tasks/gen_cli.py --write\n")
    return 1


def _reference_text() -> str:
    """Rebuild the CLI reference page around its global-flag block.

    Everything outside the two markers is prose a person maintains; the
    block between them is the seven root rows, so the page cannot describe
    a flag the declaration does not carry.
    """
    page = _REFERENCE.read_text(encoding="utf-8")
    head, opened, rest = page.partition(_OPEN + "\n")
    _body, closed, tail = rest.partition(_CLOSE + "\n")
    if not opened or not closed:
        msg = f"{_REFERENCE.name} has lost the generated block's markers"
        raise SystemExit(msg)

    return head + opened + _flag_table() + closed + tail


def _flag_table() -> str:
    """Write the global flags as a markdown table, in declaration order."""
    lines = ["| Flag | Effect |", "| ---- | ------ |"]
    for row in ALL:
        if not row.is_global:
            continue
        spelling = f"`{row.cli_flag}`"
        if row.short:
            spelling = f"`-{row.short}`, {spelling}"
        lines.append(f"| {spelling} | {row.help} |")

    return "\n".join(lines) + "\n"


def _check_pages() -> None:
    """Check that every row names a documentation page in the checkout.

    The path checked is the checkout half of the URL ``nab config
    explain`` prints, so the page a reader is sent to is one that was
    written.
    """
    for row in ALL:
        page = docs_path(row)
        if not (_ROOT / page).is_file():
            msg = f"{row.name} names {page}, which is not a documentation page"
            raise SystemExit(msg)


def _module_text() -> str:
    """Build the whole generated module from the declaration."""
    texts: list[str] = []
    root = _table_lines([row for row in ALL if row.is_global], texts, _INDENT)

    commands: list[str] = []
    for name, _module, _function in COMMANDS:
        rows = [row for row in ALL if not row.is_global and name in row.commands]
        commands.append(f'{_INDENT}"{name}": (')
        commands.extend(_table_lines(rows, texts, _INDENT * 2))
        commands.append(f"{_INDENT}),")

    parts = [
        _HEADER,
        "\n" + _help_block(texts),
        "\n# fmt: off\n",
        _block("ROOT", _ROOT_ANNOTATION, root, "("),
        "\n" + _block("COMMANDS", _COMMANDS_ANNOTATION, commands, "{"),
        "\n" + _dispatch_block(),
        "\n" + _paths_block(),
        "\n# fmt: on\n",
    ]
    return "".join(parts)


# The row type, written out where the generated module cannot import it.
_ROW_TYPE = "tuple[str, str, str, str, str, tuple[str, ...], object, object, bool, int]"

_ROOT_ANNOTATION = f"tuple[\n{_INDENT}{_ROW_TYPE}, ...\n]"

_COMMANDS_ANNOTATION = (
    f"dict[\n{_INDENT}str,\n{_INDENT}tuple[\n"
    f"{_INDENT * 2}{_ROW_TYPE}, ...\n{_INDENT}],\n]"
)


def _block(name: str, annotation: str, lines: list[str], opener: str) -> str:
    """Open and close one annotated table around its rows."""
    closer = ")" if opener == "(" else "}"
    body = "\n".join(lines)
    return f"{name}: {annotation} = {opener}\n{body}\n{closer}\n"


def _help_block(texts: list[str]) -> str:
    """Emit the interned help strings, once the tables have filled them in."""
    lines = [line for text in texts for line in _help_literal_lines(text)]
    body = "\n".join(lines)
    return f"HELP: tuple[str, ...] = (\n{body}\n)\n"


def _help_literal_lines(text: str) -> list[str]:
    """Render one help string, wrapping long values as adjacent literals."""
    literal = _literal(text)
    if len(_INDENT) + len(literal) + 1 <= _WIDTH:
        return [f"{_INDENT}{literal},"]

    width = _WIDTH - len(_INDENT * 2) - 3
    parts = textwrap.wrap(
        text,
        width=width,
        break_long_words=False,
        break_on_hyphens=False,
    )
    lines = [f"{_INDENT}("]
    for index, part in enumerate(parts):
        separator = " " if index < len(parts) - 1 else ""
        lines.append(f"{_INDENT * 2}{_literal(part + separator)}")
    lines.append(f"{_INDENT}),")
    return lines


def _dispatch_block() -> str:
    """Each command's module, function and one-line summary."""
    lines = []
    for name, module, function in COMMANDS:
        summary = _summary(module, function)
        fields = [_literal(module), _literal(function), _literal(summary)]
        lines.extend(_wrapped(f'"{name}": (', fields, "),", hanging=_INDENT * 2))

    body = "\n".join(lines)
    return f"DISPATCH: dict[str, tuple[str, str, str]] = {{\n{body}\n}}\n"


def _paths_block() -> str:
    """Emit the dests each command reads as a path, which dispatch coerces."""
    lines = []
    for name, _module, _function in COMMANDS:
        dests = [
            row.dest
            for row in ALL
            if name in row.commands and row.vtype is optiondefs.VType.PATH
        ]
        fields = [_literal(dest) for dest in dests]
        lines.extend(_wrapped(f'"{name}": (', fields, "),", hanging=_INDENT * 2))

    body = "\n".join(lines)
    return f"PATH_DESTS: dict[str, tuple[str, ...]] = {{\n{body}\n}}\n"


def _summary(module: str, function: str) -> str:
    """Read the command's first docstring line, which the root page prints."""
    imported = __import__(module, fromlist=(function,))
    documentation = getattr(imported, function).__doc__ or ""
    return documentation.strip().splitlines()[0]


def _table_lines(rows: list[Opt], texts: list[str], indent: str) -> list[str]:
    """Emit one table, with a generated negation after the row it negates."""
    lines: list[str] = []
    for row in rows:
        index = _intern(texts, row.help)
        lines.extend(_wrapped("(", _fields(row, index), "),", indent))
        if row.negatable:
            lines.extend(_wrapped("(", _negation(row, index), "),", indent))
    return lines


def _fields(row: Opt, index: int) -> list[str]:
    """Write one declared row as the ten literals the walk reads."""
    flag = row.cli_flag or ""
    vtype = "" if row.vtype is None else row.vtype.value
    if vtype and row.nullable:
        vtype += "?"

    const = row.kind in _CONST_KINDS or None
    default = None if row.default is UNSET else row.default

    fields = (
        flag,
        row.short,
        _kind(row),
        row.dest,
        vtype,
        row.choices,
        const,
        default,
        row.required,
        index,
    )
    return [_literal(field) for field in fields]


def _negation(row: Opt, index: int) -> list[str]:
    """Build the ``--no-X`` row, on the same dest with the inverted constant.

    The walk has no negation branch and cannot produce ``--no-no-X``.
    """
    flag = row.cli_flag or ""
    default = None if row.default is UNSET else row.default
    fields = (
        "--no-" + flag[2:],
        "",
        "neg",
        row.dest,
        "",
        (),
        False,
        default,
        False,
        index,
    )
    return [_literal(field) for field in fields]


def _kind(row: Opt) -> str:
    """Name the row's kind, as the walk spells it."""
    if row.kind is None:
        msg = f"{row.name} has no kind, so it has no command-line surface"
        raise SystemExit(msg)
    return row.kind.value


def _intern(texts: list[str], text: str) -> int:
    """Find ``text`` in ``texts``, adding it when it is new."""
    if text not in texts:
        texts.append(text)
    return texts.index(text)


_REGISTRY_HEADER = '''"""Generated configuration rows.

Generated by ``tasks/gen_cli.py --write`` from :mod:`nab.optiontable`. Do not
edit this file.

``OPTIONS`` contains keyed rows. ``SUB_ROWS`` contains flags that set one key
within a table.
"""

# isort: skip_file
# fmt: off
'''

# Package used to make generated nab imports relative.
_REGISTRY_PACKAGE = "nab.config"

# Opt keyword defaults in declaration order. generated is not stored on a row,
# so the __slots__ filter drops it.
_OPT_FIELDS: dict[str, object] = {
    name: parameter.default
    for name, parameter in inspect.signature(Opt.__init__).parameters.items()
    if parameter.kind is inspect.Parameter.KEYWORD_ONLY and name in Opt.__slots__
}

# Opt supplies defaults for omitted hooks, so compare these fields separately.
_HOOKS = frozenset({"parse", "render"})


class _Imports:
    """Imports required by a generated module."""

    def __init__(self) -> None:
        """Start with nothing imported."""
        self._names: dict[str, set[str]] = {}

    def add(self, module: str, name: str) -> str:
        """Import ``name`` from ``module`` and return its source name."""
        self._names.setdefault(_source(module), set()).add(name)
        return name

    def block(self) -> str:
        """Write one ``from`` import per module, parenthesised past one name."""
        lines: list[str] = []
        for module in sorted(self._names):
            names = sorted(self._names[module])
            if len(names) == 1:
                lines.append(f"from {module} import {names[0]}")
                continue

            lines.append(f"from {module} import (")
            lines.extend(f"{_INDENT}{name}," for name in names)
            lines.append(")")

        return "\n".join(lines)


def _source(module: str) -> str:
    """Return the module's import path from the generated package."""
    if module == _REGISTRY_PACKAGE:
        return "."
    root = _REGISTRY_PACKAGE.partition(".")[0]
    if module.startswith(root + "."):
        return ".." + module[len(root) + 1 :]
    return module


def _registry_text() -> str:
    """Build the generated registry from keyed and sub-table rows."""
    imports = _Imports()
    keyed = [row for row in ALL if row.key is not None]
    options = _tuple_text("OPTIONS", keyed, imports)
    sub_rows = _tuple_text("SUB_ROWS", [row for row in ALL if row.under], imports)

    body = f"{options}\n\n{sub_rows}"
    return f"{_REGISTRY_HEADER}\n{imports.block()}\n\n{body}\n\n# fmt: on\n"


def _tuple_text(name: str, rows: Sequence[Opt], imports: _Imports) -> str:
    """Write one named tuple of rows, in declaration order."""
    lines = [line for row in rows for line in _opt_lines(row, imports)]
    body = "\n".join(lines)
    return f"{name}: tuple[Opt, ...] = (\n{body}\n)"


def _opt_lines(row: Opt, imports: _Imports) -> list[str]:
    """Write an ``Opt`` call with only values that differ from its defaults."""
    call = imports.add(Opt.__module__, Opt.__name__)
    lines = [f"{_INDENT}{call}(", f"{_INDENT * 2}{_literal(row.name)},"]
    for name, unwritten in _OPT_FIELDS.items():
        if name in _HOOKS and row.under:
            continue

        value = getattr(row, name)
        if value != unwritten:
            lines.extend(_keyword(f"{name}=", value, imports, row))

    # The per-row rules already ran on the declaration this row came from.
    lines.append(f"{_INDENT * 2}generated=True,")
    lines.append(f"{_INDENT}),")
    return lines


def _keyword(head: str, value: object, imports: _Imports, row: Opt) -> list[str]:
    """Write one ``Opt`` keyword, wrapping a tuple that exceeds the limit."""
    indent = _INDENT * 2
    line = f"{indent}{head}{_spell(value, imports, row)},"
    if isinstance(value, tuple) and len(line) > _WIDTH:
        items = [_spell(item, imports, row) for item in value]
        return _wrapped(f"{head}(", items, "),", indent)

    return [line]


def _spell(value: object, imports: _Imports, row: Opt) -> str:
    """Render ``value`` as source, adding required imports."""
    if isinstance(value, enum.Enum):
        return f"{_named(type(value), imports)}.{value.name}"
    if isinstance(value, FunctionType):
        package, _, module = value.__module__.rpartition(".")
        return f"{imports.add(package, module)}.{value.__name__}"
    if isinstance(value, (str, int)) or value is None:
        return _literal(value)
    if isinstance(value, tuple):
        inner = ", ".join(_spell(item, imports, row) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    if isinstance(value, MappingProxyType):
        return _proxy(value, imports, row)
    if is_dataclass(value) and not isinstance(value, type):
        return _instance(value, imports, row)

    msg = f"{row.name} holds {value!r}, which the generator cannot render"
    raise SystemExit(msg)


def _named(cls: type, imports: _Imports) -> str:
    """Import ``cls`` and return its name."""
    return imports.add(cls.__module__, cls.__name__)


def _proxy(value: MappingProxyType[Any, Any], imports: _Imports, row: Opt) -> str:
    """Write a read-only mapping as the ``MappingProxyType`` call that builds it."""
    entries = ", ".join(
        f"{_spell(key, imports, row)}: {_spell(item, imports, row)}"
        for key, item in value.items()
    )
    call = imports.add("types", "MappingProxyType")
    return f"{call}({{{entries}}})"


def _instance(value: DataclassInstance, imports: _Imports, row: Opt) -> str:
    """Write a dataclass instance as the call that builds it, by the fields it sets."""
    written = ", ".join(
        f"{field.name}={_spell(getattr(value, field.name), imports, row)}"
        for field in fields(value)
        if field.default is MISSING or getattr(value, field.name) != field.default
    )
    return f"{_named(type(value), imports)}({written})"


def _wrapped(
    opener: str,
    fields: list[str],
    closer: str,
    indent: str = _INDENT,
    hanging: str = "",
) -> list[str]:
    """Wrap ``opener``, then ``fields``, then ``closer``, greedily.

    A row's continuation sits at the row's own indent rather than under
    the opening bracket, because one choice set is 79 characters and a
    deeper hanging indent would push it past the width.
    """
    if len(fields) == 1 and opener.endswith("("):
        fields = [fields[0] + ","]

    head = indent + opener
    hanging = hanging or indent

    lines: list[str] = []
    line = head
    for field in fields:
        piece = field if line in (head, hanging) else f", {field}"
        if len(line) + len(piece) + len(closer) <= _WIDTH:
            line += piece
        else:
            lines.append(f"{line},")
            line = hanging + field

    lines.append(line + closer)
    return lines


def _literal(value: object) -> str:
    """Write ``value`` as the source text of a literal, in the house's quotes."""
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, tuple):
        if not value:
            return "()"
        inner = ", ".join(_literal(item) for item in value)
        return f"({inner},)" if len(value) == 1 else f"({inner})"
    return repr(value)


if __name__ == "__main__":
    raise SystemExit(main())
