"""The declaration against the four command signatures, for the checkers.

Generated by ``tasks/gen_bijection.py --write`` from :mod:`nab.optiontable`.
Do not edit it: the next run of the generator would drop the edit, and
``tests/test_cli_bijection.py`` fails while the two disagree.

Nothing calls these functions.  Each is one command's parameters bound to
the rows that declare them, which is a type error where the two disagree.
"""

from __future__ import annotations

from nab._cache_cmd import cache_command
from nab._config_cmd import config_command
from nab._download import download
from nab._lock import lock
from nab.optiontable import (
    CacheWords,
    ConfigWords,
    ProjectKeys,
    RunFlags,
    UserKeys,
)


def _cache_command() -> None:
    """``nab cache``: 2 parameters."""
    cache_command(
        CacheWords.action,
        cache_dir=UserKeys.cache_dir,
    )


def _config_command() -> None:
    """``nab config``: 20 parameters."""
    config_command(
        ConfigWords.action,
        ConfigWords.key,
        project_resolution=ProjectKeys.resolution,
        project_decision_order=ProjectKeys.decision_order,
        project_mode=ProjectKeys.mode,
        project_constraint=ProjectKeys.constraints,
        project_default_group=ProjectKeys.default_groups,
        project_base_group=ProjectKeys.base_group,
        project_build_group=ProjectKeys.build_group,
        project_requires_python=ProjectKeys.requires_python,
        project_uploaded_prior_to=ProjectKeys.uploaded_prior_to,
        project_dist_policy=ProjectKeys.dist_policy,
        project_build_policy=ProjectKeys.build_policy,
        project_build_requires_depth=ProjectKeys.build_requires_depth,
        offline=UserKeys.offline,
        cache_dir=UserKeys.cache_dir,
        http_backend=UserKeys.http_backend,
        max_concurrency=UserKeys.max_concurrency,
        path=CacheWords.path,
        include_rejected=RunFlags.include_rejected,
    )


def _lock() -> None:
    """``nab lock``: 29 parameters."""
    lock(
        ConfigWords.path,
        project_resolution=ProjectKeys.resolution,
        project_decision_order=ProjectKeys.decision_order,
        project_mode=ProjectKeys.mode,
        project_constraint=ProjectKeys.constraints,
        project_default_group=ProjectKeys.default_groups,
        project_base_group=ProjectKeys.base_group,
        project_build_group=ProjectKeys.build_group,
        project_requires_python=ProjectKeys.requires_python,
        project_uploaded_prior_to=ProjectKeys.uploaded_prior_to,
        project_dist_policy=ProjectKeys.dist_policy,
        project_build_policy=ProjectKeys.build_policy,
        project_build_requires_depth=ProjectKeys.build_requires_depth,
        offline=UserKeys.offline,
        cache_dir=UserKeys.cache_dir,
        http_backend=UserKeys.http_backend,
        output=CacheWords.output,
        format=RunFlags.format,
        cache=RunFlags.cache,
        python=RunFlags.python,
        groups=RunFlags.groups,
        all_groups=RunFlags.all_groups,
        extras=RunFlags.extras,
        all_extras=RunFlags.all_extras,
        workspace_discovery=RunFlags.workspace_discovery,
        build_requirements=RunFlags.build_requirements,
        no_emit_workspace=RunFlags.no_emit_workspace,
        upgrade=RunFlags.upgrade,
        locked=RunFlags.locked,
    )


def _download() -> None:
    """``nab download``: 25 parameters."""
    download(
        ConfigWords.path,
        project_resolution=ProjectKeys.resolution,
        project_decision_order=ProjectKeys.decision_order,
        project_mode=ProjectKeys.mode,
        project_constraint=ProjectKeys.constraints,
        project_default_group=ProjectKeys.default_groups,
        project_base_group=ProjectKeys.base_group,
        project_build_group=ProjectKeys.build_group,
        project_requires_python=ProjectKeys.requires_python,
        project_uploaded_prior_to=ProjectKeys.uploaded_prior_to,
        project_dist_policy=ProjectKeys.dist_policy,
        project_build_policy=ProjectKeys.build_policy,
        project_build_requires_depth=ProjectKeys.build_requires_depth,
        offline=UserKeys.offline,
        cache_dir=UserKeys.cache_dir,
        http_backend=UserKeys.http_backend,
        max_concurrency=UserKeys.max_concurrency,
        output=RunFlags.output,
        cache=RunFlags.cache,
        python=RunFlags.python,
        groups=RunFlags.groups,
        all_groups=RunFlags.all_groups,
        extras=RunFlags.extras,
        all_extras=RunFlags.all_extras,
        workspace_discovery=RunFlags.workspace_discovery,
    )
