lock-version = "1.0"
environments = [
    "python_version == \"3.10\" and sys_platform == \"linux\" and platform_machine == \"x86_64\"",
    "python_version == \"3.10\" and sys_platform == \"linux\" and platform_machine == \"aarch64\"",
    "python_version == \"3.10\" and sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "python_version == \"3.10\" and sys_platform == \"darwin\" and platform_machine == \"x86_64\"",
    "python_version == \"3.10\" and sys_platform == \"win32\" and platform_machine == \"AMD64\"",
    "python_version == \"3.11\" and sys_platform == \"linux\" and platform_machine == \"x86_64\"",
    "python_version == \"3.11\" and sys_platform == \"linux\" and platform_machine == \"aarch64\"",
    "python_version == \"3.11\" and sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "python_version == \"3.11\" and sys_platform == \"darwin\" and platform_machine == \"x86_64\"",
    "python_version == \"3.11\" and sys_platform == \"win32\" and platform_machine == \"AMD64\"",
    "python_version == \"3.12\" and sys_platform == \"linux\" and platform_machine == \"x86_64\"",
    "python_version == \"3.12\" and sys_platform == \"linux\" and platform_machine == \"aarch64\"",
    "python_version == \"3.12\" and sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "python_version == \"3.12\" and sys_platform == \"darwin\" and platform_machine == \"x86_64\"",
    "python_version == \"3.12\" and sys_platform == \"win32\" and platform_machine == \"AMD64\"",
    "python_version == \"3.13\" and sys_platform == \"linux\" and platform_machine == \"x86_64\"",
    "python_version == \"3.13\" and sys_platform == \"linux\" and platform_machine == \"aarch64\"",
    "python_version == \"3.13\" and sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "python_version == \"3.13\" and sys_platform == \"darwin\" and platform_machine == \"x86_64\"",
    "python_version == \"3.13\" and sys_platform == \"win32\" and platform_machine == \"AMD64\"",
    "python_version == \"3.14\" and sys_platform == \"linux\" and platform_machine == \"x86_64\"",
    "python_version == \"3.14\" and sys_platform == \"linux\" and platform_machine == \"aarch64\"",
    "python_version == \"3.14\" and sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "python_version == \"3.14\" and sys_platform == \"darwin\" and platform_machine == \"x86_64\"",
    "python_version == \"3.14\" and sys_platform == \"win32\" and platform_machine == \"AMD64\"",
]
requires-python = ">=3.10"
created-by = "nab"

[[packages]]
name = "hatchling"
version = "1.31.0"
requires-python = ">=3.10"
dependencies = [
    { name = "packaging" },
    { name = "pathspec" },
    { name = "pluggy" },
    { name = "tomli" },
    { name = "trove-classifiers" },
]
index = "https://pypi.org/simple/"

[packages.sdist]
name = "hatchling-1.31.0.tar.gz"
upload-time = 2026-07-08 01:48:32.237659+00:00
url = "https://files.pythonhosted.org/packages/25/e2/dfa73fe78f773018dcaebc6d09b819bc10d328ff5a6b4a66efa1e3d71f52/hatchling-1.31.0.tar.gz"
size = 57208

[packages.sdist.hashes]
sha256 = "6b48ad4068a482ed7239b3a8215bc55b47aad3345d58dfc94e553c5d2d46211b"

[[packages.wheels]]
name = "hatchling-1.31.0-py3-none-any.whl"
upload-time = 2026-07-08 01:48:31.024633+00:00
url = "https://files.pythonhosted.org/packages/64/e2/2c0af0a52d16be74a4f194564fcdc417521ed863e9b65e4bc9052dacba6f/hatchling-1.31.0-py3-none-any.whl"
size = 77747

[packages.wheels.hashes]
sha256 = "aac80bec8b6fe35e8480f1c335be8910fa210a0e6f735a139be205dadcacb544"

[[packages]]
name = "packaging"
version = "26.3"
requires-python = ">=3.9"
index = "https://pypi.org/simple/"

[packages.sdist]
name = "packaging-26.3.tar.gz"
upload-time = 2026-08-04 18:15:28.737071+00:00
url = "https://files.pythonhosted.org/packages/7d/fa/3944b40b07da9ce895c0e6303a5ab7d53da063554f534556b134a54d6093/packaging-26.3.tar.gz"
size = 313412

[packages.sdist.hashes]
sha256 = "94edc256424af38762eb31306eed28beb9f0efc50a8837492c9d6fd6004aed79"

[[packages.wheels]]
name = "packaging-26.3-py3-none-any.whl"
upload-time = 2026-08-04 18:15:27.159957+00:00
url = "https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl"
size = 129956

[packages.wheels.hashes]
sha256 = "d7193f7c8e4e93f444fde0262bf90af30e16fa0ad0ad44cb553c87339b23cd1c"

[[packages]]
name = "pathspec"
version = "1.1.1"
requires-python = ">=3.9"
index = "https://pypi.org/simple/"

[packages.sdist]
name = "pathspec-1.1.1.tar.gz"
upload-time = 2026-04-27 01:46:08.907631+00:00
url = "https://files.pythonhosted.org/packages/5a/82/42f767fc1c1143d6fd36efb827202a2d997a375e160a71eb2888a925aac1/pathspec-1.1.1.tar.gz"
size = 135180

[packages.sdist.hashes]
sha256 = "17db5ecd524104a120e173814c90367a96a98d07c45b2e10c2f3919fff91bf5a"

[[packages.wheels]]
name = "pathspec-1.1.1-py3-none-any.whl"
upload-time = 2026-04-27 01:46:07.060850+00:00
url = "https://files.pythonhosted.org/packages/f1/d9/7fb5aa316bc299258e68c73ba3bddbc499654a07f151cba08f6153988714/pathspec-1.1.1-py3-none-any.whl"
size = 57328

[packages.wheels.hashes]
sha256 = "a00ce642f577bf7f473932318056212bc4f8bfdf53128c78bbd5af0b9b20b189"

[[packages]]
name = "pluggy"
version = "1.6.0"
requires-python = ">=3.9"
index = "https://pypi.org/simple/"

[packages.sdist]
name = "pluggy-1.6.0.tar.gz"
upload-time = 2025-05-15 12:30:07.975376+00:00
url = "https://files.pythonhosted.org/packages/f9/e2/3e91f31a7d2b083fe6ef3fa267035b518369d9511ffab804f839851d2779/pluggy-1.6.0.tar.gz"
size = 69412

[packages.sdist.hashes]
sha256 = "7dcc130b76258d33b90f61b658791dede3486c3e6bfb003ee5c9bfb396dd22f3"

[[packages.wheels]]
name = "pluggy-1.6.0-py3-none-any.whl"
upload-time = 2025-05-15 12:30:06.134003+00:00
url = "https://files.pythonhosted.org/packages/54/20/4d324d65cc6d9205fabedc306948156824eb9f0ee1633355a8f7ec5c66bf/pluggy-1.6.0-py3-none-any.whl"
size = 20538

[packages.wheels.hashes]
sha256 = "e920276dd6813095e9377c0bc5566d94c932c33b27a3e3945d8389c374dd4746"

[[packages]]
name = "tomli"
version = "2.4.1"
marker = "python_version == \"3.10\""
requires-python = ">=3.8"
index = "https://pypi.org/simple/"

[packages.sdist]
name = "tomli-2.4.1.tar.gz"
upload-time = 2026-03-25 20:22:03.828102+00:00
url = "https://files.pythonhosted.org/packages/22/de/48c59722572767841493b26183a0d1cc411d54fd759c5607c4590b6563a6/tomli-2.4.1.tar.gz"
size = 17543

[packages.sdist.hashes]
sha256 = "7c7e1a961a0b2f2472c1ac5b69affa0ae1132c39adcb67aba98568702b9cc23f"

[[packages.wheels]]
name = "tomli-2.4.1-py3-none-any.whl"
upload-time = 2026-03-25 20:22:03.012768+00:00
url = "https://files.pythonhosted.org/packages/7b/61/cceae43728b7de99d9b847560c262873a1f6c98202171fd5ed62640b494b/tomli-2.4.1-py3-none-any.whl"
size = 14583

[packages.wheels.hashes]
sha256 = "0d85819802132122da43cb86656f8d1f8c6587d54ae7dcaf30e90533028b49fe"

[[packages]]
name = "trove-classifiers"
version = "2026.6.1.19"
index = "https://pypi.org/simple/"

[packages.sdist]
name = "trove_classifiers-2026.6.1.19.tar.gz"
upload-time = 2026-06-01 19:41:34.649417+00:00
url = "https://files.pythonhosted.org/packages/c2/e3/7ca82ee24c82d344584abd5b8637b3bd056f2900226e8d82fc22f1184b92/trove_classifiers-2026.6.1.19.tar.gz"
size = 17059

[packages.sdist.hashes]
sha256 = "c5132b4b61a829d11cfbd2d72e97f20a45ed6edb95e45c5efdeb5e00836b2745"

[[packages.wheels]]
name = "trove_classifiers-2026.6.1.19-py3-none-any.whl"
upload-time = 2026-06-01 19:41:33.434069+00:00
url = "https://files.pythonhosted.org/packages/7c/a4/81502f486f01db95bc8320646a8a12511f5e556cb63d5e224d91816605c4/trove_classifiers-2026.6.1.19-py3-none-any.whl"
size = 14211

[packages.wheels.hashes]
sha256 = "ab4c4ec93cc4a4e7815fa759906e05e6bb3f2fbd92ea0f897288c6a43efd15b3"

[tool.nab]
nab-version = "0.0.14.dev0"
created-at = 2026-08-12 13:49:39.688262+00:00
command-line = [
    "nab",
    "lock",
    "--build-requirements",
    "--no-emit-workspace",
    "--output",
    ".github/requirements/pylock.build.toml",
    "--upgrade",
]
input-path = "pyproject.toml"
mode = "universal"
python-specifier = ">=3.10,<3.15"
platforms = [
    "linux_x86_64",
    "linux_aarch64",
    "macos_arm64",
    "macos_x86_64",
    "windows_amd64",
]
